service: hello-serverless

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs4.3
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: arn:aws:dynamodb:*:*:table/helloTable

functions:
  addHello:
    handler: handler.hello
    events:
      - http:
          method: post
          path: hello
          integration: lambda-proxy
  getHellos:
    handler: handler.hellos
    events:
      - http:
          method: get
          path: hellos/{messageId}
          integration: lambda-proxy
          request:
            parameters:
              paths:
                messageId: true

resources:
  Resources:
    helloTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: helloTable
        AttributeDefinitions:
          - AttributeName: messageId
            AttributeType: S
        KeySchema:
          - AttributeName: messageId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
#    helloTableIamPolicy:
#      Type: AWS::IAM::Policy
#      DependsOn: helloTable
#      Properties:
#        PolicyName: hello-dynamodb
#        PolicyDocument:
#          Version: '2012-10-17'
#          Statement:
#            - Effect: Allow
#              Action:
#                - dynamodb:GetItem
#                - dynamodb:PutItem
#              Resources: arn:aws:dynamodb:*:*:table/helloTable
#        Roles:
#          - Ref: IamRoleLambdaExecution
